FROM node:23-alpine3.20

WORKDIR /app

# only the package.json is copied to leverage the docker cache
COPY package.json .

RUN yarn install

# copy the rest of the files
COPY . .

RUN yarn build

EXPOSE 4000

CMD [ "yarn", "start:dev" ]